development:
  adapter: postgresql
  database: junior_test_task
  host: localhost
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  adapter: postgresql
  database: junior_test_task_test
  host: localhost
  port: 5432
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: junior_test_task_production
  username: junior_test_task
  password: <%= ENV['JUNIOR_TEST_TASK_DATABASE_PASSWORD'] %>